# Generated by Django 3.2.13 on 2022-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decimal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
