# Generated by Django 3.2.13 on 2022-08-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_decimal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='decimal',
            new_name='decimals',
        ),
    ]
