# Generated by Django 3.2.13 on 2022-09-08 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='testnet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('url', models.URLField(max_length=100)),
                ('secret_hash', models.CharField(max_length=22)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_urls', to='account.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
