# Generated by Django 3.2.13 on 2022-09-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220908_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='secret_hash',
        ),
    ]
