# Generated by Django 3.2.13 on 2022-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_added_is_verified_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
        migrations.AddField(
            model_name='apikey',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
    ]
