# Generated by Django 3.2.13 on 2022-08-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220807_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='account.account'),
        ),
    ]
