# Generated by Django 3.2.15 on 2022-09-03 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('txn_reference', models.CharField(max_length=42, unique=True)),
                ('sender', models.CharField(max_length=58)),
                ('txn_type', models.CharField(choices=[('payment_link', 'Payment Link')], default='payment_link', max_length=50)),
                ('recipient', models.CharField(max_length=58)),
                ('txn_hash', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asset', to_field='asa_id')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('image', models.ImageField(null=True, upload_to='payment-links')),
                ('is_active', models.BooleanField(default=True)),
                ('has_fixed_amount', models.BooleanField(default=False)),
                ('is_one_time', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asset', to_field='asa_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
