# Generated by Django 3.2.13 on 2022-06-07 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('has_fixed_amount', models.BooleanField()),
                ('is_one_time', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_ref', models.CharField(max_length=10)),
                ('sender', models.CharField(max_length=58)),
                ('recipient', models.CharField(max_length=58)),
                ('txn_hash', models.TextField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.asset')),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.paymentlink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
