# Generated by Django 3.2.13 on 2022-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
