# Generated by Django 3.2.15 on 2022-09-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0002_add_network_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asset', to_field='asa_id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asset', to_field='asa_id'),
        ),
    ]
