# Generated by Django 3.2.15 on 2022-09-24 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('account', '0002_change_default_network_to_mainnet'),
        ('payments', '0002_normal_tx_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='testnet', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
