# Generated by Django 3.2.13 on 2022-07-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentlinktransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='image',
            field=models.ImageField(null=True, upload_to='link_images'),
        ),
    ]
