# Generated by Django 3.2.15 on 2022-10-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_dailyrevenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrevenue',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='dailyrevenue',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
    ]
