# Generated by Django 3.2.13 on 2022-08-01 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0005_auto_20220728_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('txn_ref', models.CharField(max_length=20, unique=True)),
                ('sender', models.CharField(blank=True, max_length=58, null=True)),
                ('txn_type', models.CharField(choices=[('payment_link', 'Payment Link')], default='payment_link', max_length=50)),
                ('recipient', models.CharField(max_length=58)),
                ('txn_hash', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.asset')),
                ('payment_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='payments.paymentlink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PaymentLinkTransaction',
        ),
    ]
