# Generated by Django 3.2.13 on 2022-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20220728_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
    ]
