# Generated by Django 3.2.13 on 2022-08-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentlink_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlinktransaction',
            name='network',
            field=models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=20),
        ),
    ]
