# Generated by Django 3.2.13 on 2022-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220801_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txn_ref',
            field=models.CharField(max_length=46, unique=True),
        ),
    ]
