# Generated by Django 3.2.13 on 2022-08-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_transaction_txn_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
    ]
