# Generated by Django 3.2.13 on 2022-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20220801_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(default='XQ52337XYJMFNUM73IC5KSLG6UXYKMK3H36LW6RI2DRBSGIJRQBI6X6OYI', max_length=58),
            preserve_default=False,
        ),
    ]
